Frontend/Models/ErrorViewModel.cs
namespace Frontend.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Frontend/Controllers/AccountController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Shared.Data.Model;
using Shared.Utils;

namespace Frontend.Controllers
{
    public class AccountController : Controller
    {
        private readonly IConfiguration _configuration;
        public AccountController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Login()
        {
            return View();
        }

        public async Task<ActionResult> ValidateAsync(Shared.Data.Model.RequestAuth admin)
        {
            try
            {
                string BaseUri = _configuration.GetSection("Uri").GetSection("BaseUri").Value.ToString();
                string GetTokenPath = _configuration.GetSection("Uri").GetSection("GetToken").Value.ToString();
                string LoginPath = _configuration.GetSection("Uri").GetSection("Login").Value.ToString();
                string Key = _configuration.GetSection("JwtAccess").GetSection("Key").Value.ToString();
                string Value = _configuration.GetSection("JwtAccess").GetSection("Value").Value.ToString();

                string FinalUri = BaseUri + GetTokenPath;
                var response = await new Helpers().RequestToken(FinalUri, Key, Value);
                if (!string.IsNullOrEmpty(response.token))
                {
                    FinalUri = BaseUri + LoginPath;
                    RequestAuth data = new RequestAuth();
                    BaseRequest<RequestAuth> payload = new BaseRequest<RequestAuth>();

                    data.username = admin.username;
                    data.password = admin.password;
                    payload.Value = data;

                    var respLogin = await new Helpers.HTTPService().PostWithTokenResultValue<RequestAuth,ResponseLogin>(FinalUri, response.token, payload);
                    if (!respLogin.Item2.ErrorStatus)
                    {
                        HttpContext.Session.SetString("UserID", respLogin.Item2.Value.user_id.ToString());
                        return Json(new { status = true, message = "Login Successfull!" });
                    }
                    else
                    {
                        return Json(new { status = true, message = respLogin.Item2.ErrorMessage });
                    }
                }
                else
                {
                    return Json(new { status = false, message = "Upss, Something wrong!" });
                }
            }
            catch (Exception e)
            {
                return Json(new { status = false, message = e.Message });
            }
        }
    }
}

Frontend/Controllers/BpkbController.cs
using System;
using System.Diagnostics.Metrics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Shared.Data.Contract;
using Shared.Data.Model;
using Shared.Utils;

namespace Frontend.Controllers
{
	public class BpkbController : Controller
	{
        private readonly IConfiguration _configuration;
        public BpkbController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> CreateAsync()
        {
            //List<ms_storage_location> cl = new List<ms_storage_location>();
            List<SelectListItem> cl = new List<SelectListItem>();
            SelectListItem temp = new SelectListItem();
            temp.Text = "Pilih Lokasi Penyimpanan";
            temp.Value = "0";
            cl.Add(temp);
            try
            {
                string BaseUri = _configuration.GetSection("Uri").GetSection("BaseUri").Value.ToString();
                string GetTokenPath = _configuration.GetSection("Uri").GetSection("GetToken").Value.ToString();
                string GetLocation = _configuration.GetSection("Uri").GetSection("GetLocation").Value.ToString();
                string Key = _configuration.GetSection("JwtAccess").GetSection("Key").Value.ToString();
                string Value = _configuration.GetSection("JwtAccess").GetSection("Value").Value.ToString();

                string FinalUri = BaseUri + GetTokenPath;
                var response = await new Helpers().RequestToken(FinalUri, Key, Value);
                if (!string.IsNullOrEmpty(response.token))
                {
                    FinalUri = BaseUri + GetLocation;
                    BaseRequest<Abstract> payload = new BaseRequest<Abstract>();
                    var respGetLocation = await new Helpers.HTTPService().PostWithTokenResultValue<Abstract,List<ms_storage_location>>(FinalUri, response.token, payload);
                    if (respGetLocation.Item2.Value!=null)
                    {
                        cl.AddRange(respGetLocation.Item2.Value.Select(x=> new SelectListItem { Text=x.location_name,Value= x.location_id }).ToList());
                    }
                }
            }
            catch (Exception e)
            {
            }

            ViewBag.LocationList = cl;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> InsertDataAsync(InsertData insertData)
        {
            try
            {
                string BaseUri = _configuration.GetSection("Uri").GetSection("BaseUri").Value.ToString();
                string GetTokenPath = _configuration.GetSection("Uri").GetSection("GetToken").Value.ToString();
                string InsertBpkbPath = _configuration.GetSection("Uri").GetSection("InsertData").Value.ToString();
                string Key = _configuration.GetSection("JwtAccess").GetSection("Key").Value.ToString();
                string Value = _configuration.GetSection("JwtAccess").GetSection("Value").Value.ToString();

                string FinalUri = BaseUri + GetTokenPath;
                var response = await new Helpers().RequestToken(FinalUri, Key, Value);
                if (!string.IsNullOrEmpty(response.token))
                {
                    FinalUri = BaseUri + InsertBpkbPath;
                    InsertData data = new InsertData();
                    BaseRequest<InsertData> payload = new BaseRequest<InsertData>();
                    string UserID = HttpContext.Session.GetString("UserID") ?? "";
                    if (!string.IsNullOrEmpty(UserID))
                    {
                        insertData.user_id = Convert.ToInt64(HttpContext.Session.GetString("UserID"));
                        payload.Value = insertData;

                        var respInsert = await new Helpers.HTTPService().PostWithTokenResultValue<InsertData, ResponseInsert>(FinalUri, response.token, payload);
                        if (!respInsert.Item2.ErrorStatus)
                        {
                            return Json(new { status = true, message = "Insert Data Successfull!" });
                        }
                        else
                        {
                            return Json(new { status = true, message = respInsert.Item2.ErrorMessage });
                        }
                    }
                    else
                    {
                        return Json(new { status = false, message = "Upss, Something wrong!" });
                    }
                }
                else
                {
                    return Json(new { status = false, message = "Upss, Something wrong!" });
                }
            }
            catch (Exception e)
            {
                return Json(new { status = false, message = e.Message });
            }
        }
    }
}

Frontend/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Frontend.Models;

namespace Frontend.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Frontend/Views/Bpkb/Create.cshtml
<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content container-fluid">
    <!-- Horizontal Form -->
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Insert Data BPKB</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post">
            <div class="box-body">
                <div class="col-md-12">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="inputAgreementNumber" class="col-md-4 control-label">Agreement Number</label>
                            <div class="col-md-8">
                                <input type="text" class="form-control" name="agreement_number" id="agreement_number" placeholder="Agreement Number">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputbranch_id" class="col-md-4 control-label">Branch ID</label>
                            <div class="col-md-8">
                                <input type="text" required="required" class="form-control" name="branch_id" id="branch_id" placeholder="Input Branch ID">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputbpkb_no" class="col-md-4 control-label">No. BPKB</label>
                            <div class="col-md-8">
                                <input type="text" required="required" class="form-control" name="bpkb_no" id="bpkb_no" placeholder="Input No. BPKB">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputbpkb_date_in" class="col-md-4 control-label">Tanggal BPKB in</label>
                            <div class="col-md-8">
                                <div class="input-group date" data-provide="datepicker">
                                    <input type="text" class="form-control pull-right" id="bpkb_date_in" name="bpkb_date_in">
                                    <div class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputbpkb_date_in" class="col-md-4 control-label">Tanggal BPKB</label>
                            <div class="col-md-8">
                                <div class="input-group date" data-provide="datepicker">
                                    <input type="text" class="form-control pull-right" id="bpkb_date" name="bpkb_date">
                                    <div class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputfaktur_no" class="col-md-4 control-label">No. Faktur</label>
                            <div class="col-md-8">
                                <input type="text" required="required" class="form-control" name="faktur_no" id="faktur_no" placeholder="Input No. Faktur">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="inputfaktur_date" class="col-md-4 control-label">Tanggal Faktur</label>
                            <div class="col-md-8">
                                <div class="input-group date" data-provide="datepicker">
                                    <input type="text" class="form-control pull-right" id="faktur_date" name="faktur_date" >
                                    <div class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputpolice_no" class="col-md-4 control-label">No. Polisi</label>
                            <div class="col-md-8">
                                <input type="text" required="required" class="form-control" name="police_no" id="police_no" placeholder="Input No. Polisi">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputfaktur_date" class="col-md-4 control-label">Lokasi Penyimpanan</label>
                            <div class="col-md-8">
                                <select name="location_id" id="location_id" class="form-control" asp-items="@ViewBag.LocationList"></select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-info pull-right" onclick="InsertData()">Create</button>
            </div>
            <!-- /.box-footer -->
        </form>
    </div>
    <script>
    function InsertData() {
      $.ajax({
        type: "POST",
        url: '@Url.Action("InsertData", "Bpkb")',
        data: {
          agreement_number: $('#agreement_number').val(),
          bpkb_no: $('#bpkb_no').val(),
          branch_id: $('#branch_id').val(),
          faktur_no: $('#faktur_no').val(),
          faktur_date: $('#faktur_date').val(),
          location_id: $('#location_id').val(),
          police_no: $('#police_no').val(),
          bpkb_date_in: $('#bpkb_date_in').val(),
          bpkb_date: $('#bpkb_date').val(),
          user_id: 0
        },
        error: function(result) {
          alert("There is a Problem, Try Again!");
        },
        success: function(result) {
          if (result.status == true) {
            alert("Berhasil disimpan");
          } else {
            alert("Gagal disimpan");
          }
        }
      });
    }
    </script>
    <script type="text/javascript">
        $('.input-group.date').datepicker({
            todayBtn: "linked",
            language: "it",
            autoclose: true,
            todayHighlight: true,
            Format: 'yyyy-MM-dd'
        });
    </script>`
    <!-- /.box -->
</section>

Frontend/Views/Home/Index.cshtml
<section class="content-header">
    <h1>
        Home
        <small>Optional description</small>
    </h1>
</section>
<!-- Main content -->
<section class="content container-fluid">
    <!--------------------------
    | Your Page Content Here |
    -------------------------->
</section>

Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin Panel</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/dist/css/skins/skin-blue.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link rel="stylesheet" href="~/bower_components/bootstrap-daterangepicker/daterangepicker.css">
    <link rel="stylesheet" href="~/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>AP</b>T</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>AdminPanel</span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="~/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">Actuator</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="~/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        Actuator
                                        <small>Member since Nov. 2024</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Account</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>Actuator</p>
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                @Html.Partial("_MainMenu")
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong>Copyright &copy; 2018 <a href="https://codinginfinite.com">CodingInfinite</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 3 -->
    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <script src="~/bower_components/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script src="~/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script>$(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
            //Datemask2 mm/dd/yyyy
            $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
            //Money Euro
            $('[data-mask]').inputmask()

            //Date range picker
            $('#reservation').daterangepicker()
            //Date range picker with time picker
            $('#reservationtime').daterangepicker({ timePicker: true, timePickerIncrement: 30, locale: { format: 'MM/DD/YYYY hh:mm A' } })
            //Date range as a button
            $('#daterange-btn').daterangepicker(
                {
                    ranges: {
                        'Today': [moment(), moment()],
                        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                        'This Month': [moment().startOf('month'), moment().endOf('month')],
                        'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    },
                    startDate: moment().subtract(29, 'days'),
                    endDate: moment()
                },
                function (start, end) {
                    $('#daterange-btn span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
                }
            )

            //Date picker
            $('#datepicker').datepicker({
                format: "dd/mm/yyyy",
                autoclose: true
            })


            //iCheck for checkbox and radio inputs
            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-blue',
                radioClass: 'iradio_minimal-blue'
            })
            //Red color scheme for iCheck
            $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
                checkboxClass: 'icheckbox_minimal-red',
                radioClass: 'iradio_minimal-red'
            })
            //Flat red color scheme for iCheck
            $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-green'
            })

            //Colorpicker
            $('.my-colorpicker1').colorpicker()
            //color picker with addon
            $('.my-colorpicker2').colorpicker()

            //Timepicker
            $('.timepicker').timepicker({
                showInputs: false
            })
        })</script>
</body>
</html>

Frontend/Views/Shared/_MainMenu.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <li class="treeview active menu-open">
        <a href="#">
            <i class="fa fa-edit"></i> <span>Forms</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li class="active"><a href="/Bpkb/Create"><i class="fa fa-circle-o"></i> Input BPKB</a></li>
        </ul>
    </li>
</ul>